# Generated by Django 2.1.3 on 2020-08-06 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('usertype', models.IntegerField(db_column='usertype', default=1)),
                ('username', models.CharField(db_column='username', max_length=255)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('createtime', models.DateTimeField(db_column='createtime', default=django.utils.timezone.now)),
                ('updatetime', models.DateTimeField(db_column='updatetime', default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False)),
            ],
        ),
    ]
