# Generated by Django 2.1.3 on 2020-08-07 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0004_visit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='child_view',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('child_view_name', models.CharField(db_column='child_view_name', max_length=255)),
                ('view_position_x', models.FloatField(db_column='view_position_x', default=0)),
                ('view_position_y', models.FloatField(db_column='view_position_y', default=0)),
                ('view_position_z', models.FloatField(db_column='view_position_z', default=0)),
                ('createtime', models.DateTimeField(db_column='createtime', default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='child_view_model_conf',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('child_view_id', models.IntegerField(db_column='child_view_id', default=0)),
                ('model_id', models.IntegerField(db_column='model_id', default=0)),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False)),
                ('position_x', models.FloatField(db_column='position_x')),
                ('position_y', models.FloatField(db_column='position_y')),
                ('position_z', models.FloatField(db_column='position_z')),
                ('rotation_x', models.FloatField(db_column='rotation_x')),
                ('rotation_y', models.FloatField(db_column='rotation_y')),
                ('rotation_z', models.FloatField(db_column='rotation_z')),
                ('materials_color_r', models.FloatField(db_column='materials_color_r', default=0.13)),
                ('materials_color_g', models.FloatField(db_column='materials_color_g', default=0.13)),
                ('materials_color_b', models.FloatField(db_column='materials_color_b', default=0.13)),
                ('scale_x', models.FloatField(db_column='scale_x', default=1)),
                ('scale_y', models.FloatField(db_column='scale_y', default=1)),
                ('scale_z', models.FloatField(db_column='scale_z', default=1)),
                ('materials_type', models.IntegerField(db_column='materials_type', default=1)),
                ('metalness', models.FloatField(db_column='metalness', default=1)),
                ('roughness', models.FloatField(db_column='roughness', default=0.5)),
                ('emissive_r', models.FloatField(db_column='emissive_r', default=1)),
                ('emissive_g', models.FloatField(db_column='emissive_g', default=1)),
                ('emissive_b', models.FloatField(db_column='emissive_b', default=1)),
                ('emissiveIntensity', models.FloatField(db_column='emissiveIntensity', default=0)),
                ('reflectivity', models.FloatField(db_column='reflectivity', default=0.5)),
                ('createtime', models.DateTimeField(db_column='f_createtime', default=django.utils.timezone.now)),
                ('updatetime', models.DateTimeField(db_column='f_updatetime', default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='child_view_parent_view_ralation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('parent_view_id', models.IntegerField(db_column='parent_view_id', default=1)),
                ('child_view_id', models.IntegerField(db_column='child_view_id', default=1)),
                ('createtime', models.DateTimeField(db_column='createtime', default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='com_model',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_column='model_name', max_length=255)),
                ('url', models.CharField(db_column='url', max_length=255)),
                ('createtime', models.DateTimeField(db_column='createtime', default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='model_base_model_relation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('model_id', models.IntegerField(db_column='model_id', default=1)),
                ('model_base_id', models.IntegerField(db_column='model_base_id', default=1)),
                ('createtime', models.DateTimeField(db_column='createtime', default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='parent_view',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('parent_view_name', models.CharField(db_column='parent_view_name', max_length=255)),
                ('createtime', models.DateTimeField(db_column='createtime', default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify_token',
        ),
        migrations.AlterField(
            model_name='model_base',
            name='createtime',
            field=models.DateTimeField(db_column='createtime', default=django.utils.timezone.now),
        ),
    ]
