# Generated by Django 2.1.3 on 2020-08-07 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0005_auto_20200807_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_view_model_conf',
            name='createtime',
            field=models.DateTimeField(db_column='createtime', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='child_view_model_conf',
            name='updatetime',
            field=models.DateTimeField(db_column='updatetime', default=django.utils.timezone.now),
        ),
    ]
