# Generated by Django 2.1.3 on 2020-08-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0006_auto_20200807_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_model',
            name='url',
            field=models.URLField(db_column='url', max_length=500),
        ),
        migrations.AlterField(
            model_name='model_base_model_relation',
            name='model_base_id',
            field=models.ForeignKey(db_column='model_base_id', on_delete=django.db.models.deletion.CASCADE, to='vmaker.model_base'),
        ),
        migrations.AlterField(
            model_name='model_base_model_relation',
            name='model_id',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, to='vmaker.com_model'),
        ),
    ]
