# Generated by Django 2.1.3 on 2020-08-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0007_auto_20200807_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_view',
            name='owner_id',
            field=models.IntegerField(db_column='owner_id', default=1),
        ),
    ]
