# Generated by Django 2.1.3 on 2020-08-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0008_parent_view_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child_view_parent_view_ralation',
            name='child_view_id',
            field=models.ForeignKey(db_column='child_view_id', on_delete=django.db.models.deletion.CASCADE, to='vmaker.child_view'),
        ),
        migrations.AlterField(
            model_name='child_view_parent_view_ralation',
            name='parent_view_id',
            field=models.ForeignKey(db_column='parent_view_id', on_delete=django.db.models.deletion.CASCADE, to='vmaker.parent_view'),
        ),
    ]
