# Generated by Django 2.1.3 on 2020-08-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0010_auto_20200808_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_view_model_conf',
            name='serial',
            field=models.CharField(db_column='serial', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='child_view_model_conf',
            name='position_x',
            field=models.FloatField(db_column='position_x', default=0),
        ),
        migrations.AlterField(
            model_name='child_view_model_conf',
            name='position_y',
            field=models.FloatField(db_column='position_y', default=0),
        ),
        migrations.AlterField(
            model_name='child_view_model_conf',
            name='position_z',
            field=models.FloatField(db_column='position_z', default=0),
        ),
        migrations.AlterField(
            model_name='child_view_model_conf',
            name='rotation_x',
            field=models.FloatField(db_column='rotation_x', default=0),
        ),
        migrations.AlterField(
            model_name='child_view_model_conf',
            name='rotation_y',
            field=models.FloatField(db_column='rotation_y', default=0),
        ),
        migrations.AlterField(
            model_name='child_view_model_conf',
            name='rotation_z',
            field=models.FloatField(db_column='rotation_z', default=0),
        ),
    ]
