# Generated by Django 2.1.5 on 2020-08-25 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0016_auto_20200819_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_view',
            name='updatetime',
            field=models.DateTimeField(db_column='updatetime', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parent_view',
            name='version',
            field=models.CharField(db_column='version', default='', max_length=255),
        ),
    ]
