# Generated by Django 2.1.5 on 2020-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmaker', '0017_auto_20200825_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_view',
            name='version',
            field=models.CharField(db_column='version', default='', max_length=255),
        ),
    ]
